# Generated by Django 4.2.3 on 2023-07-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='書籍類別')),
            ],
            options={
                'verbose_name': '書籍類別',
                'verbose_name_plural': '書籍類別',
            },
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='必填', upload_to='', verbose_name='貼文圖片')),
                ('sort', models.SmallIntegerField(verbose_name='圖片排序')),
            ],
            options={
                'verbose_name': '貼文圖庫',
                'verbose_name_plural': '貼文圖庫',
            },
        ),
        migrations.CreateModel(
            name='writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='作者姓名')),
            ],
            options={
                'verbose_name': '作者列表',
                'verbose_name_plural': '作者列表',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('main_title', models.CharField(help_text='必填', max_length=30, verbose_name='主標題')),
                ('book_title', models.CharField(max_length=30, verbose_name='書名')),
                ('content', models.TextField(verbose_name='貼文內容')),
                ('sour', models.SmallIntegerField(default=0, verbose_name='風味-酸')),
                ('sweet', models.SmallIntegerField(default=0, verbose_name='風味-甜')),
                ('bitter', models.SmallIntegerField(default=0, verbose_name='風味-苦')),
                ('spicy', models.SmallIntegerField(default=0, verbose_name='風味-辣')),
                ('salt', models.SmallIntegerField(default=0, verbose_name='風味-鹹')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('categorys', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='book_site.bookcategory')),
                ('post_imgs', models.ManyToManyField(blank=True, null=True, to='book_site.images', verbose_name='圖片')),
                ('writer', models.ForeignKey(blank=True, help_text='必填', on_delete=django.db.models.deletion.PROTECT, to='book_site.writers')),
            ],
            options={
                'verbose_name': '雙周更貼文',
                'verbose_name_plural': '雙周更貼文',
            },
        ),
    ]
