# Generated by Django 4.2.3 on 2023-07-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0002_review_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=30, verbose_name='職位名稱')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='職員名稱')),
                ('sex', models.IntegerField(choices=[(0, '男性'), (1, '女性'), (3, '未知')], default=0)),
                ('rank', models.ForeignKey(blank=True, help_text='必填', on_delete=django.db.models.deletion.CASCADE, to='book_site.userrank')),
            ],
        ),
    ]
